//! Service keyring: deterministic seeded dev mode and env-key prod
//! mode. All real cryptography flows through [`unidpp_signatif`]; this
//! module owns the seed bytes and the derived
//! [`unidpp_signatif::keyring::KeyPair`] handles that sign every
//! response body.
//!
//! Two roles, mirroring the issuer's signing split but co-signed onto
//! every response (the multi-suite discipline is the
//! jurisdiction-specific signature model — a P-256-only verifier can
//! still check responses without the Ed25519 path):
//!
//! - **sign-ed25519** — Ed25519 (ed25519-dalek). SIGNATIF's
//!   infrastructure suite; signature rides the
//!   `x-sig-ed25519` header.
//! - **sign-ecdsa-p256** — ECDSA-P256, deterministic RFC 6979 via the
//!   `p256` crate. The ECDSA signature rides the `x-sig-ecdsa-p256`
//!   header and is the form the core's Tier-A carrier budget natively
//!   encodes (it is also what the CLI `--anchor` accepts as the 65-byte
//!   SEC1 form).
//!
//! Mode resolution:
//!
//! - **env-key mode**: both `UNIDPP_TRUST_SIGN_SEED` (Ed25519) and
//!   `UNIDPP_TRUST_SIGN_SEED_P256` (ECDSA-P256) set to hex of at least
//!   [`MIN_SEED_BYTES`] bytes. The raw bytes become the signing seeds
//!   (production keeps the CSPRNG outside this crate).
//! - **seeded-dev mode**: at least one seed is missing. The service
//!   derives both keys deterministically from a single human-readable
//!   dev seed (`UNIDPP_TRUST_DEV_SEED`, else a fixed default) — same
//!   seed always produces the same keyring, so resolvers, witnesses and
//!   tests stay reproducible. `Config::from_env` reports the fallback
//!   via the `/keyring` "warning" field so deployments do not silently
//!   run in dev mode.

use serde_json::{json, Value};
use unidpp_signatif::keyring::{KeyId, KeyPair, PublicKey};
use unidpp_signatif::sign::Suite;

use crate::hex::{hex_decode, hex_encode};

/// The fallback dev seed when `UNIDPP_TRUST_DEV_SEED` is unset. Never
/// used in production deployments (env-key mode overrides it).
pub const DEFAULT_DEV_SEED: &str = "unidpp-trust/dev-1";

/// Minimum decoded seed length (hex-encoded minimum 16 bytes — short
/// material is rejected to avoid accidentally-weak dev seeds).
pub const MIN_SEED_BYTES: usize = 16;

/// The two signing roles the trust service recognises.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum Role {
    /// Ed25519 (SIGNATIF infrastructure suite).
    SignEd25519,
    /// ECDSA-P256 (RFC 6979 deterministic).
    SignEcdsaP256,
}

impl Role {
    pub fn as_str(self) -> &'static str {
        match self {
            Role::SignEd25519 => "sign-ed25519",
            Role::SignEcdsaP256 => "sign-ecdsa-p256",
        }
    }
}

/// How the keyring was assembled — exposed to operators via `/keyring`
/// and the discovery document.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum KeyringMode {
    /// Deterministic keys derived from a fixed seed (dev mode only;
    /// never use in production).
    SeededDev,
    /// Keys loaded from environment-supplied hex seeds.
    EnvKey,
}

impl KeyringMode {
    pub fn as_str(self) -> &'static str {
        match self {
            KeyringMode::SeededDev => "seeded-dev",
            KeyringMode::EnvKey => "env-key",
        }
    }
}

/// The service keyring. Construct via [`Keyring::dev`] or
/// [`Keyring::from_env_seeds`].
#[derive(Debug)]
pub struct Keyring {
    mode: KeyringMode,
    ed_key: KeyPair,
    p256_key: KeyPair,
    /// The human-readable seed that produced this keyring (only set in
    /// seeded-dev mode — env-key mode reports `None`).
    dev_seed: Option<String>,
}

impl Keyring {
    /// Deterministic dev-mode keyring derived from `seed`. When
    /// `seed.is_empty()`, falls back to [`DEFAULT_DEV_SEED`].
    pub fn dev(seed: Option<&str>) -> Keyring {
        let dev_seed = match seed {
            Some(s) if !s.trim().is_empty() => s.trim().to_string(),
            _ => DEFAULT_DEV_SEED.to_string(),
        };
        let ed_material = format!("unidpp-trust/sign-ed25519|{dev_seed}");
        let p256_material = format!("unidpp-trust/sign-ecdsa-p256|{dev_seed}");
        // KeyPair::seeded only errors for deferred suites (Sm2/MlDsa);
        // Ed25519/P256 always succeed — unwrap is safe by construction.
        let ed_key = KeyPair::seeded(Suite::Ed25519, ed_material.as_bytes())
            .expect("Ed25519 seed derivation");
        let p256_key = KeyPair::seeded(Suite::EcdsaP256, p256_material.as_bytes())
            .expect("P-256 seed derivation");
        Keyring {
            mode: KeyringMode::SeededDev,
            ed_key,
            p256_key,
            dev_seed: Some(dev_seed),
        }
    }

    /// Env-key mode: raw seeds supplied by the operator (typically
    /// generated by a separate CSPRNG-backed ceremony and pasted as
    /// hex). Both hex inputs are required and must each decode to at
    /// least [`MIN_SEED_BYTES`] bytes.
    pub fn from_env_seeds(ed_hex: &str, p256_hex: &str) -> Result<Keyring, String> {
        let ed_seed =
            hex_decode(ed_hex.trim()).map_err(|e| format!("Ed25519 seed: not hex: {e}"))?;
        let p256_seed =
            hex_decode(p256_hex.trim()).map_err(|e| format!("ECDSA-P256 seed: not hex: {e}"))?;
        if ed_seed.len() < MIN_SEED_BYTES {
            return Err(format!(
                "Ed25519 seed too short: {} bytes (need at least {MIN_SEED_BYTES})",
                ed_seed.len()
            ));
        }
        if p256_seed.len() < MIN_SEED_BYTES {
            return Err(format!(
                "ECDSA-P256 seed too short: {} bytes (need at least {MIN_SEED_BYTES})",
                p256_seed.len()
            ));
        }
        let ed_key = KeyPair::seeded(Suite::Ed25519, &ed_seed)
            .map_err(|e| format!("Ed25519 key derivation: {e}"))?;
        let p256_key = KeyPair::seeded(Suite::EcdsaP256, &p256_seed)
            .map_err(|e| format!("ECDSA-P256 key derivation: {e}"))?;
        Ok(Keyring {
            mode: KeyringMode::EnvKey,
            ed_key,
            p256_key,
            dev_seed: None,
        })
    }

    /// Resolve a keyring from environment variables. Bad seeds are
    /// reported via the returned warnings; on any failure the service
    /// falls back to deterministic dev mode (the `/keyring` "warning"
    /// field tells operators which mode they are in).
    pub fn from_env(dev_seed: Option<&str>) -> (Keyring, Vec<String>) {
        let mut warnings = Vec::new();
        let ed = std::env::var("UNIDPP_TRUST_SIGN_SEED").ok();
        let p256 = std::env::var("UNIDPP_TRUST_SIGN_SEED_P256").ok();
        match (ed.as_deref(), p256.as_deref()) {
            (Some(e), Some(p)) => match Keyring::from_env_seeds(e, p) {
                Ok(k) => (k, warnings),
                Err(err) => {
                    warnings.push(format!(
                        "UNIDPP_TRUST_SIGN_SEED / UNIDPP_TRUST_SIGN_SEED_P256 rejected: {err}; \
                         falling back to seeded-dev mode"
                    ));
                    (Keyring::dev(dev_seed), warnings)
                }
            },
            _ => (Keyring::dev(dev_seed), warnings),
        }
    }

    pub fn mode(&self) -> KeyringMode {
        self.mode
    }

    pub fn dev_seed(&self) -> Option<&str> {
        self.dev_seed.as_deref()
    }

    pub fn ed25519(&self) -> &KeyPair {
        &self.ed_key
    }

    pub fn p256(&self) -> &KeyPair {
        &self.p256_key
    }

    /// Public view for the role.
    pub fn public(&self, role: Role) -> &PublicKey {
        match role {
            Role::SignEd25519 => self.ed_key.public(),
            Role::SignEcdsaP256 => self.p256_key.public(),
        }
    }

    /// Content-derived key id for the role.
    pub fn key_id(&self, role: Role) -> &KeyId {
        match role {
            Role::SignEd25519 => self.ed_key.key_id(),
            Role::SignEcdsaP256 => self.p256_key.key_id(),
        }
    }

    /// Hex-encoded raw public key bytes for the role (CLI `--anchor`
    /// accepts this form: 32 bytes for Ed25519, 65 bytes for SEC1 P-256).
    pub fn public_hex(&self, role: Role) -> String {
        hex_encode(self.public(role).as_bytes())
    }

    /// Public view for `/keyring`: mode, roles, suites, key ids,
    /// hex-encoded public anchors a verifier pins, and a verification
    /// recipe matching the response headers.
    pub fn to_json(&self) -> Value {
        let mut roles = serde_json::Map::new();
        for role in [Role::SignEd25519, Role::SignEcdsaP256] {
            let public = self.public(role);
            roles.insert(
                role.as_str().to_string(),
                json!({
                    "suite": public.suite().to_string(),
                    "key_id": self.key_id(role).to_string(),
                    "public": hex_encode(public.as_bytes()),
                    "public_len": public.as_bytes().len(),
                }),
            );
        }
        let mut m = serde_json::Map::new();
        m.insert("mode".into(), json!(self.mode.as_str()));
        m.insert("roles".into(), Value::Object(roles));
        m.insert("domain".into(), json!("tree-head"));
        m.insert(
            "headers".into(),
            json!({
                "as_of": "x-as-of",
                "ed25519_sig": "x-sig-ed25519",
                "ed25519_key": "x-sig-key-id-ed25519",
                "ecdsa_p256_sig": "x-sig-ecdsa-p256",
                "ecdsa_p256_key": "x-sig-key-id-ecdsa-p256",
                "domain": "x-sig-domain",
                "etag": "etag",
                "cache_control": "cache-control",
            }),
        );
        m.insert(
            "verification".into(),
            json!("GET responses carry x-sig-ed25519 and x-sig-ecdsa-p256 over the exact body bytes in the tree-head domain. Verify by SignatureSlot::verify(SigningDomain::TreeHead, body_bytes, public_key); pin either role via CLI --anchor."),
        );
        if let Some(seed) = &self.dev_seed {
            m.insert("dev_seed".into(), json!(seed));
            m.insert(
                "warning".into(),
                json!("seeded-dev mode is for development only; production deployments must use env-key mode"),
            );
        }
        Value::Object(m)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn dev_mode_is_deterministic_and_roles_distinct() {
        let a = Keyring::dev(Some("test-seed"));
        let b = Keyring::dev(Some("test-seed"));
        let c = Keyring::dev(Some("other-seed"));
        assert_eq!(a.mode(), KeyringMode::SeededDev);
        assert_eq!(a.ed25519().key_id(), b.ed25519().key_id());
        assert_eq!(a.p256().key_id(), b.p256().key_id());
        assert_ne!(a.ed25519().key_id(), c.ed25519().key_id());
        assert_ne!(a.ed25519().key_id(), a.p256().key_id());
        // Different roles use distinct suites — collision would defeat
        // multi-suite anchor pinning.
        assert_ne!(
            a.ed25519().public().as_bytes(),
            a.p256().public().as_bytes()
        );
    }

    #[test]
    fn empty_seed_falls_back_to_default() {
        let k = Keyring::dev(Some(""));
        assert_eq!(k.dev_seed(), Some(DEFAULT_DEV_SEED));
        assert_eq!(k.mode(), KeyringMode::SeededDev);
    }

    #[test]
    fn env_mode_round_trip_and_minimum_length() {
        // Two distinct 32-byte hex seeds.
        let ed = "0011223344556677889900aabbccddeeff00112233445566778899aabbccddee";
        let p = "ffeeddccbbaa99887766554433221100ffeeddccbbaa99887766554433221100";
        let k = Keyring::from_env_seeds(ed, p).unwrap();
        assert_eq!(k.mode(), KeyringMode::EnvKey);
        assert!(k.dev_seed().is_none());
        assert_eq!(k.public(Role::SignEd25519).suite(), Suite::Ed25519);
        assert_eq!(k.public(Role::SignEcdsaP256).suite(), Suite::EcdsaP256);
        // Both publics re-derive from the seeds (the seed is hashed,
        // so the public key is a function of it — not the seed
        // itself).
        let re_ed = KeyPair::seeded(Suite::Ed25519, &hex_decode(ed).unwrap()).unwrap();
        assert_eq!(k.public(Role::SignEd25519), re_ed.public());
        let re_p = KeyPair::seeded(Suite::EcdsaP256, &hex_decode(p).unwrap()).unwrap();
        assert_eq!(k.public(Role::SignEcdsaP256), re_p.public());
        // And two different seeds give different keys.
        let k2 = Keyring::from_env_seeds(p, ed).unwrap();
        assert_ne!(
            k.public_hex(Role::SignEd25519),
            k2.public_hex(Role::SignEd25519)
        );
    }

    #[test]
    fn env_mode_rejects_short_and_bad_hex() {
        let short = "deadbeef";
        let good = "00112233445566778899aabbccddeeff";
        assert!(Keyring::from_env_seeds(short, good).is_err());
        assert!(Keyring::from_env_seeds(good, short).is_err());
        assert!(Keyring::from_env_seeds("nonsense!!", good).is_err());
    }

    #[test]
    fn public_hex_lengths_match_cli_anchor_expectation() {
        let k = Keyring::dev(Some("anchor-test"));
        assert_eq!(k.public_hex(Role::SignEd25519).len(), 64); // 32 bytes hex
        assert_eq!(k.public_hex(Role::SignEcdsaP256).len(), 130); // 65 bytes hex
    }

    #[test]
    fn to_json_includes_roles_warning_and_headers() {
        let k = Keyring::dev(Some("j"));
        let v = k.to_json();
        assert_eq!(v["mode"], "seeded-dev");
        assert_eq!(v["roles"]["sign-ed25519"]["suite"], "ed25519");
        assert_eq!(v["roles"]["sign-ecdsa-p256"]["suite"], "ecdsa-p256");
        assert_eq!(v["roles"]["sign-ed25519"]["public_len"], 32);
        assert_eq!(v["roles"]["sign-ecdsa-p256"]["public_len"], 65);
        assert!(v["warning"].as_str().unwrap().contains("seeded-dev"));
        assert!(v["headers"]["ed25519_sig"]
            .as_str()
            .unwrap()
            .starts_with("x-sig-"));
    }
}
